apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      lables:
        app: flask-app
    spec:
      containers:
      - name: flaskapp
        image: sanjeevrisbud/flaskapp:latest
        env:
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "admin"
          - name: MYSQL_DB
            value: "myDB"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always